=== MatthewMerricks/Cloud/Users/Zack/CloudSDK_SmokeTest/Settings/InputParameters.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="InputParameters"
    targetNamespace="http://www.cloud.com/InputParameters.xsd"
    elementFormDefault="qualified"
    xmlns="http://www.cloud.com/InputParameters.xsd"
    xmlns:mstns="http://www.cloud.com/InputParameters.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema" >
  <xs:annotation>
    <xs:appinfo>Cloud.com InputParameters XML Schema</xs:appinfo>
    <xs:documentation xml:lang="en-us">
      InputParameters.xsd and resulting generated code
      Cloud

      Created by BobS.

      Copyright (c) Cloud.com. All rights reserved.

      Manually copy this copyright declaration to the header of any generated code files created from this schema
    </xs:documentation>
  </xs:annotation>

  <xs:complexType name="Copyright">
    <xs:sequence>
      <xs:element name="FileName" minOccurs="0" maxOccurs="1" type="xs:string" />
      <xs:element name="Copyright" minOccurs="1" maxOccurs="1">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Implementation of InputParameters.xsd XML Schema. Cloud. Copyright (c) Cloud.com. All rights reserved." />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Creator" minOccurs="1" maxOccurs="1" type="xs:string" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="InputParams">
    <xs:all>
      <xs:element name="API_Key" type="xs:string" minOccurs="1"/>
      <xs:element name="API_Secret" type="xs:string" minOccurs="1"/>
      <xs:element name="ActiveSyncBoxID" type="xs:int" minOccurs="1"/>
      <xs:element name="ActiveSync_Folder" type="xs:string" minOccurs="1"/>
      <xs:element name="ActiveSync_Folder2" type="xs:string" minOccurs="0" />
      <xs:element name="ActiveSync_TraceFolder" type="xs:string" minOccurs="1"/>
      <xs:element name="ManualSyncBoxID" type="xs:int" minOccurs="1"/>
      <xs:element name="ManualSync_Folder" type="xs:string" minOccurs="1"/>
      <xs:element name="ManualSync_TraceFolder" type="xs:string" minOccurs="1"/>
      <xs:element name="Token" type="xs:string" minOccurs="0"/>
      <xs:element name="TraceType" type="xs:int" minOccurs="1"/>
      <xs:element name="TraceLevel" type="xs:int" minOccurs="1"/>
      <xs:element name ="SettingsPath" type="xs:string" minOccurs="1" />
      <xs:element name="FileNameMappingFile" type="xs:string" minOccurs="1" />
    </xs:all>
  </xs:complexType>

  <xs:complexType name="ModificationObject">
    <xs:sequence>
      <xs:element name="type" >
        <xs:simpleType>
          <xs:restriction base ="xs:string" >
            <xs:enumeration value="File" />
            <xs:enumeration value="Folder" />
            <xs:enumeration value="SyncBox" />
            <xs:enumeration value="Session" />
            <xs:enumeration value="Plan" />
            <xs:enumeration value="None" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="SmokeTask">
    <xs:sequence>
      <xs:element name="type" >
        <xs:simpleType>
          <xs:restriction base ="xs:string" >
            <xs:enumeration value = "CreateSyncBox" />
            <xs:enumeration value = "Creation" />
            <xs:enumeration value = "Deletion" />
            <xs:enumeration value = "DownloadAllSyncBoxContent" />
            <xs:enumeration value = "Rename" />
            <xs:enumeration value = "FileUndelete" />
            <xs:enumeration value = "HttpTest" />
            <xs:enumeration value = "ListItems" />
            <xs:enumeration value = "Comparison" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="SyncType" minOccurs="1">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Active"/>
            <xs:enumeration value ="Manual" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="InnerTask" minOccurs="0" type="SmokeTask" />
      <xs:element name="ObjectType" type="ModificationObject" />
      <xs:element name="SelectedSyncBoxID" type="xs:long" />
      <xs:element name="AtIndex" type="xs:int" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>



  <xs:complexType name="Creation">
    <xs:complexContent >
      <xs:extension base="SmokeTask" >
        <xs:sequence>
          <xs:element name="Name" type ="xs:string" />
          <xs:element name="Path" type ="xs:string" />
          <xs:element name="CreateNew" type="xs:boolean" />
          <xs:element name="Count" type="xs:int" minOccurs="0" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Deletion">
    <xs:complexContent >
      <xs:extension base="SmokeTask" >
        <xs:sequence>
          <xs:element name="Name" type ="xs:string" minOccurs="0" />
          <xs:element name="FullName" type ="xs:string" minOccurs="0" />
          <xs:element name="RelativePath" type ="xs:string" minOccurs="0" />
          <xs:element name="FullPath" type ="xs:string" minOccurs="0" />
          <xs:element name="DeleteAll" type="xs:boolean" minOccurs="0" />
          <xs:element name="DeleteCount" type="xs:int" minOccurs="0"/>
          <xs:element name="ID" type="xs:long" minOccurs="0"/>
          <xs:element name="ServerID" type="xs:string" minOccurs="0" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Rename">
    <xs:complexContent >
      <xs:extension base="SmokeTask" >
        <xs:sequence>
          <xs:element name="OldName" type ="xs:string" minOccurs="0" maxOccurs="1"/>
          <xs:element name="NewName" type ="xs:string" minOccurs="0" maxOccurs="1"/>
          <xs:element name="RelativeDirectoryPath" type ="xs:string" minOccurs="0" maxOccurs="1"/>
          <xs:element name="ServerID" type="xs:long" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Undelete">
    <xs:complexContent >
      <xs:extension base="SmokeTask" >
        <xs:sequence>
          <xs:element name="FullPath" type ="xs:string" />
          <xs:element name="FileName" type ="xs:string" />
          <xs:element name="Version" type ="xs:string" />
          <xs:element name="IsFile" type="xs:boolean" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="DownloadAllSyncBoxContent">
    <xs:complexContent >
      <xs:extension base="SmokeTask" >
        <xs:sequence>
          <xs:element name="FolderPath" type ="xs:string" />
          <xs:element name="FilePath" type ="xs:string" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="CreateSyncBox">
    <xs:complexContent >
      <xs:extension base="SmokeTask" >
        <xs:sequence>
          <xs:element name="CreateNew" type="xs:boolean"/>
          <xs:element name="Count" type="xs:int" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="HttpTest">
    <xs:complexContent >
      <xs:extension base="SmokeTask" >
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="ListItems">
    <xs:complexContent >
      <xs:extension base="SmokeTask" >
        <xs:sequence>
          <xs:element name="ListType">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="Sessions" />
                <xs:enumeration value="Plans" />
                <xs:enumeration value="SyncBoxes" />
              </xs:restriction>
            </xs:simpleType>
          </xs:element>
          <xs:element name="ExpectedCount" type="xs:int" minOccurs="0"></xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Comparison" >
    <xs:complexContent>
      <xs:extension base="SmokeTask">
        <xs:sequence>
          <xs:element name="ComparisonType">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="ManualToActive" />
                <xs:enumeration value="ActiveToServer" />
                <xs:enumeration value="ActiveToActive" />
              </xs:restriction>
            </xs:simpleType>
          </xs:element>
          <xs:element name="UseDynamicSyncBox" type="xs:boolean" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="ParallelTaskSet">
    <xs:choice >
      <xs:element minOccurs="0" maxOccurs="unbounded" name="SmokeTask" type="SmokeTask" />
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="Scenario">
    <xs:choice>
      <xs:element name="ScenarioTasks" type="ParallelTaskSet" minOccurs="0" maxOccurs="unbounded" />
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="MockFile" >
    <xs:sequence>
      <xs:element name="type" >
        <xs:simpleType>
          <xs:restriction base ="xs:string" >
            <xs:enumeration value ="FileByPath" />
            <xs:enumeration value="RandomDataFile" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="FileByPath">
    <xs:complexContent >
      <xs:extension base="MockFile" >
        <xs:sequence>
          <xs:element name="FilePath" type ="xs:string" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="RandomDataFile">
    <xs:complexContent >
      <xs:extension base="MockFile" >
        <xs:sequence>
          <xs:element name="FilePath" type ="xs:string" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <!--<xs:element name="SmokeTest">
    <xs:complexType>
      <xs:all>
        <xs:element name="Copyright" type="Copyright" />
        <xs:element name="InputParams" type="InputParams" />
        <xs:element name="ParallelTaskSet" type="ParallelTaskSet" />
      </xs:all>
    </xs:complexType>
  </xs:element>-->
  <xs:element name="SmokeTest">
    <xs:complexType>
      <xs:all>
        <xs:element name="Copyright" type="Copyright" />
        <xs:element name="InputParams" type="InputParams" />
        <xs:element name="Scenario" type="Scenario"  />
      </xs:all>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== MatthewMerricks/Cloud/Users/Zack/CloudSDK_SmokeTest/Settings/Tests/RTF_FileTransferTest.xml
<?xml version="1.0" encoding="utf-8"?>
<SmokeTest xmlns="http://www.cloud.com/InputParameters.xsd"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.cloud.com InputParameters.xsd">
  <!-- Task For Testing Posting an RTF File-->
  <!-- Start 2 Active Sync Sessions 
         Create an RTF file in the Directory for Active Sync 1 
         Confirm the RTF file was Synced to Active Sync Directory 2-->
  <ScenarioTasks>
    <SmokeTask xsi:type="Deletion">
      <type>Deletion</type>
      <SyncType>Active</SyncType>
      <ObjectType>
        <type>SyncBox</type>
      </ObjectType>
      <SelectedSyncBoxID>0</SelectedSyncBoxID>
      <DeleteAll>true</DeleteAll>
    </SmokeTask>
    <SmokeTask xsi:type="CreateSyncBox">
      <type>CreateSyncBox</type>
      <SyncType>Active</SyncType>
      <ObjectType>
        <type>SyncBox</type>
      </ObjectType>
      <SelectedSyncBoxID>0</SelectedSyncBoxID>
      <CreateNew>true</CreateNew>
      <Count>1</Count>
    </SmokeTask>
    <SmokeTask xsi:type="Prompt">
      <type>Prompt</type>
      <SyncType>Active</SyncType>
      <ObjectType>
        <type>None</type>
      </ObjectType>
      <SelectedSyncBoxID>0</SelectedSyncBoxID>
      <Message>Please Begin 2 Active SyncBox Sessions on the Same SyncBox Id</Message>
    </SmokeTask>
    <SmokeTask xsi:type="Creation">
      <type>Creation</type>
      <SyncType>Active</SyncType>
      <ObjectType>
        <type>File</type>
      </ObjectType>
      <SelectedSyncBoxID>0</SelectedSyncBoxID>
      <Name>IAmRichTextFile.rtf</Name>
      <Path>\</Path>
      <CreateNew>true</CreateNew>
      <Count>3</Count>
      <ActInTwoFolders>false</ActInTwoFolders>
    </SmokeTask>
    <SmokeTask xsi:type="Comparison">
      <type>Comparison</type>
      <SyncType>Active</SyncType>
      <ObjectType>
        <type>None</type>
      </ObjectType>
      <SelectedSyncBoxID>0</SelectedSyncBoxID>
      <ComparisonType>ActiveToActive</ComparisonType>
      <UseDynamicSyncBox>true</UseDynamicSyncBox>
      <ShouldWait>true</ShouldWait>
    </SmokeTask>
  </ScenarioTasks>
  <!-- End Task For Testing Posting an RTF File-->

</SmokeTest>

=== MatthewMerricks/Cloud/Users/Zack/CloudSDK_SmokeTest/Settings/Tests/EditHostA_WhileBGetsOfflineEdits.xml
<?xml version="1.0" encoding="utf-8" ?>
<SmokeTest xmlns="http://www.cloud.com/InputParameters.xsd"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.cloud.com InputParameters.xsd">

  <!-- Task For Testing Host 1 Folder Rename while Host 2 Offline  -->
  <!-- Testing Scenario where 2 Hosts are Open and in Sync 
           Host 2 Goes Offline 
           Make Chnages to Host 1 (including Folder Rename)
           Host  2 Comes Back Online
           Host 2 Creates / Modifies Existing items 
           Check if Folders are in Sync-->
  <ScenarioTasks>
      <SmokeTask xsi:type="Deletion">
        <type>Deletion</type>
        <SyncType>Active</SyncType>
        <ObjectType>
          <type>SyncBox</type>
        </ObjectType>
        <SelectedSyncBoxID>0</SelectedSyncBoxID>
        <DeleteAll>true</DeleteAll>
        <ID>0</ID>
        <ServerID>0</ServerID>
      </SmokeTask>
      <SmokeTask xsi:type="CreateSyncBox">
        <type>CreateSyncBox</type>
        <SyncType>Active</SyncType>
        <ObjectType>
          <type>SyncBox</type>
        </ObjectType>
        <SelectedSyncBoxID>0</SelectedSyncBoxID>
        <CreateNew>true</CreateNew>
        <Count>1</Count>
      </SmokeTask>
      <SmokeTask xsi:type="Prompt">
        <type>Prompt</type>
        <SyncType>Active</SyncType>
        <ObjectType>
          <type>None</type>
        </ObjectType>
        <SelectedSyncBoxID>0</SelectedSyncBoxID>
        <Message>Please Begin 2 Active Sync Processes.</Message>
      </SmokeTask>
      <SmokeTask xsi:type="Creation">
        <type>Creation</type>
        <SyncType>Active</SyncType>
        <ObjectType>
          <type>File</type>
        </ObjectType>
        <SelectedSyncBoxID>0</SelectedSyncBoxID>
        <Name>BeforeStopping.txt</Name>
        <Path>\</Path>
        <CreateNew>true</CreateNew>
        <Count>5</Count>
      </SmokeTask>
      <SmokeTask xsi:type="Creation">
        <type>Creation</type>
        <SyncType>Active</SyncType>
        <ObjectType>
          <type>File</type>
        </ObjectType>
        <SelectedSyncBoxID>0</SelectedSyncBoxID>
        <Name>ProiorStopping.txt</Name>
        <Path>\Prior\</Path>
        <CreateNew>true</CreateNew>
        <Count>5</Count>
      </SmokeTask>
      <SmokeTask xsi:type="Creation">
        <type>Creation</type>
        <SyncType>Active</SyncType>
        <ObjectType>
          <type>Folder</type>
        </ObjectType>
        <SelectedSyncBoxID>0</SelectedSyncBoxID>
        <Name>PreStop</Name>
        <Path>\Prior\</Path>
        <CreateNew>true</CreateNew>
        <Count>5</Count>
      </SmokeTask>
      <SmokeTask xsi:type="Comparison">
        <type>Comparison</type>
        <SyncType>Active</SyncType>
        <ObjectType>
          <type>None</type>
        </ObjectType>
        <SelectedSyncBoxID>0</SelectedSyncBoxID>
        <ComparisonType>ActiveToActive</ComparisonType>
        <UseDynamicSyncBox>true</UseDynamicSyncBox>
        <ShouldWait>true</ShouldWait>
      </SmokeTask>
      <SmokeTask xsi:type="Prompt">
        <type>Prompt</type>
        <SyncType>Active</SyncType>
        <ObjectType>
          <type>None</type>
        </ObjectType>
        <SelectedSyncBoxID>0</SelectedSyncBoxID>
        <Message>Please Pause One Of SyncBox's Active Sync Process</Message>
      </SmokeTask>
      <SmokeTask xsi:type="Creation">
        <type>Creation</type>
        <SyncType>Active</SyncType>
        <ObjectType>
          <type>File</type>
        </ObjectType>
        <SelectedSyncBoxID>0</SelectedSyncBoxID>
        <Name>AfterStopping.txt</Name>
        <Path>\After\</Path>
        <CreateNew>true</CreateNew>
        <Count>5</Count>
      </SmokeTask>
      <SmokeTask xsi:type="Creation">
        <type>Creation</type>
        <SyncType>Active</SyncType>
        <ObjectType>
          <type>Folder</type>
        </ObjectType>
        <SelectedSyncBoxID>0</SelectedSyncBoxID>
        <Name>PostStop</Name>
        <Path>\Post\</Path>
        <CreateNew>true</CreateNew>
        <Count>5</Count>
      </SmokeTask>
      <SmokeTask xsi:type="Prompt">
        <type>Prompt</type>
        <SyncType>Active</SyncType>
        <ObjectType>
          <type>None</type>
        </ObjectType>
        <SelectedSyncBoxID>0</SelectedSyncBoxID>
        <Message>Please Restart Stopped Active Process</Message>
      </SmokeTask>
      <SmokeTask xsi:type="Rename">
        <type>Rename</type>
        <SyncType>Active</SyncType>
        <ObjectType>
          <type>Folder</type>
        </ObjectType>
        <SelectedSyncBoxID>0</SelectedSyncBoxID>
        <OldName>Prior</OldName>
        <NewName>PriorRenamed</NewName>
        <RelativeDirectoryPath>\</RelativeDirectoryPath>
        <ServerID>0</ServerID>
        <ActInTwoFolders>false</ActInTwoFolders>
      </SmokeTask>
      <SmokeTask xsi:type="Rename">
        <type>Rename</type>
        <SyncType>Active</SyncType>
        <ObjectType>
          <type>Folder</type>
        </ObjectType>
        <SelectedSyncBoxID>0</SelectedSyncBoxID>
        <OldName>PreStop</OldName>
        <NewName>PreStoppedRenamed</NewName>
        <RelativeDirectoryPath>\PriorRenamed\</RelativeDirectoryPath>
        <ServerID>0</ServerID>
        <ActInTwoFolders>false</ActInTwoFolders>
      </SmokeTask>
      <SmokeTask xsi:type="Comparison">
        <type>Comparison</type>
        <SyncType>Active</SyncType>
        <ObjectType>
          <type>None</type>
        </ObjectType>
        <SelectedSyncBoxID>0</SelectedSyncBoxID>
        <ComparisonType>ActiveToActive</ComparisonType>
        <UseDynamicSyncBox>true</UseDynamicSyncBox>
        <ShouldWait>true</ShouldWait>
      </SmokeTask>
    </ScenarioTasks>
  <!-- End Task For Testing Host 1 Folder Rename while Host 2 Offline  -->
</SmokeTest>

=== MatthewMerricks/Cloud/Users/Zack/CloudSDK_SmokeTest/Settings/Settings.xml
<?xml version="1.0" encoding="utf-8" ?>
<SmokeTest xmlns="http://www.cloud.com/InputParameters.xsd"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.cloud.com InputParameters.xsd">
  <Copyright>
    <FileName>Settings.xml</FileName>
    <Copyright>Implementation of InputParameters.xsd XML Schema. Cloud. Copyright (c) Cloud.com. All rights reserved.</Copyright>
    <Creator>BobS</Creator>
  </Copyright>
  
  <InputParams>
    <API_Key>00d86d2ef9971f5f410480e6f82b49095ec11daa81e5702448f624d53460f42f</API_Key>
    <API_Secret>ad4b65f0d89ced24a9feaa5c93e970b8e1a43008d69ad20a6809ab18f6abb5dd</API_Secret>
    <ActiveSync_Folder>"C:\TestSyncBoxes\Auto_SyncBoxA"</ActiveSync_Folder>
    <ActiveSync_TraceFolder>"C:\TestSyncBoxes\Traces\AutoSyncTraces"</ActiveSync_TraceFolder>
    <ActiveSyncBoxID>372</ActiveSyncBoxID>
    <ManualSyncBoxID>372</ManualSyncBoxID>
    <ManualSync_Folder>"C:\Users\t_zacharyw\Cloud\"</ManualSync_Folder>
    <ManualSync_TraceFolder>"C:\TestSyncBoxes\Traces\ManualSyncTraces"</ManualSync_TraceFolder>
    <Token></Token>
    <TraceLevel>5</TraceLevel>
    <TraceType>4</TraceType>
    <FileNameMappingFile>"C:\Users\t_zacharyw\Cloud\NamingConflicts.xml"</FileNameMappingFile>
  </InputParams>
  <Scenario>
    <ScenarioTasks>
      <SmokeTask xsi:type="Creation">
          <type>Creation</type>
          <SyncType>Manual</SyncType>
          <InnerTask xsi:type="Rename">
            <type>Rename</type>
            <SyncType>Manual</SyncType>
            <InnerTask xsi:type="Deletion">
              <type>Deletion</type>
              <SyncType>Manual</SyncType>
              <InnerTask xsi:type="Comparison">
                <type>Comparison</type>
                <SyncType>Manual</SyncType>
                <ObjectType>
                  <type>None</type>
                </ObjectType>
                <SelectedSyncBoxID>371</SelectedSyncBoxID>
              </InnerTask>
              <ObjectType>
                <type>File</type>
              </ObjectType>
              <SelectedSyncBoxID>0</SelectedSyncBoxID>
              <Name>T1File12.txt</Name>
              <FullName>C:\Users\t_zacharyw\Cloud</FullName>
              <RelativePath>\T1File12.txt</RelativePath>
              <FullPath>C:\Users\t_zacharyw\Cloud\T1File12.txt</FullPath>
              <DeleteAll>false</DeleteAll>
              <DeleteCount>1</DeleteCount>
              <ID>0</ID>
              <ServerID>0</ServerID>
            </InnerTask>
            <ObjectType>
              <type>File</type>
            </ObjectType>
            <SelectedSyncBoxID>0</SelectedSyncBoxID>
            <OldName>T1File.txt</OldName>
            <NewName>T1File_Rename.txt</NewName>
            <RelativeDirectoryPath>\</RelativeDirectoryPath>
            <ServerID>0</ServerID>
          </InnerTask>
          <ObjectType>
            <type>File</type>
          </ObjectType>
          <SelectedSyncBoxID>0</SelectedSyncBoxID>
          <Name>T1File.txt</Name>
          <Path>C:\Users\t_zacharyw\Cloud</Path>
          <CreateNew>true</CreateNew>
      </SmokeTask>
      <SmokeTask xsi:type ="ListItems">
        <type>ListItems</type>
        <SyncType>Manual</SyncType>
        <InnerTask xsi:type="Deletion">
          <type>Deletion</type>
          <SyncType>Manual</SyncType>
          <InnerTask xsi:type="Creation">
            <type>Creation</type>
            <SyncType>Manual</SyncType>
            <InnerTask xsi:type="ListItems">
              <type>ListItems</type>
              <SyncType>Manual</SyncType>
              <ObjectType>
                <type>Session</type>
              </ObjectType>
              <SelectedSyncBoxID>0</SelectedSyncBoxID>
              <ListType>Sessions</ListType>
              <ExpectedCount>3</ExpectedCount>
            </InnerTask>
            <ObjectType>
              <type>Session</type>
            </ObjectType>
            <SelectedSyncBoxID>0</SelectedSyncBoxID>
            <Name></Name>
            <Path></Path>
            <CreateNew>true</CreateNew>
            <Count>3</Count>
          </InnerTask>
          <ObjectType>
            <type>Session</type>
          </ObjectType>
          <SelectedSyncBoxID>0</SelectedSyncBoxID>
          <Name></Name>
          <FullName></FullName>
          <RelativePath></RelativePath>
          <FullPath></FullPath>
          <DeleteAll>true</DeleteAll>
          <DeleteCount>0</DeleteCount>
          <ID>0</ID>
          <ServerID>0</ServerID>
        </InnerTask>
        <ObjectType>
          <type>Session</type>
        </ObjectType>
        <SelectedSyncBoxID>0</SelectedSyncBoxID>
        <ListType>Sessions</ListType>
        <ExpectedCount>0</ExpectedCount>
      </SmokeTask>
  </ScenarioTasks> 
</Scenario>
</SmokeTest>

=== MatthewMerricks/Cloud/Users/Zack/CloudSDK_SmokeTest/Settings/Tests/RenameHostA_WhileHostBIsDownloading.xml
<?xml version="1.0" encoding="utf-8" ?>
<SmokeTest xmlns="http://www.cloud.com/InputParameters.xsd"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.cloud.com InputParameters.xsd">

  <!-- Task For Testing Host 1 Folder Rename While Host 2 is Mid Sync-->
  <!-- Start 1 Active Sync Session 
          Add Multiple Large Files to Host 1 Active Sync Folder
          Confirm Upload of Host 1 Files are complete 
          Start Active Sync Session for Host 2 
          Rename a Folder in Host 1 while host 2 is syncing-->

  <ScenarioTasks>
    <SmokeTask xsi:type="Deletion">
      <type>Deletion</type>
      <SyncType>Active</SyncType>
      <ObjectType>
        <type>SyncBox</type>
      </ObjectType>
      <SelectedSyncBoxID>0</SelectedSyncBoxID>
      <DeleteAll>true</DeleteAll>
    </SmokeTask>
    <SmokeTask xsi:type="CreateSyncBox">
      <type>CreateSyncBox</type>
      <SyncType>Active</SyncType>
      <ObjectType>
        <type>SyncBox</type>
      </ObjectType>
      <SelectedSyncBoxID>0</SelectedSyncBoxID>
      <CreateNew>true</CreateNew>
      <Count>1</Count>
    </SmokeTask>
    <SmokeTask xsi:type="Prompt">
      <type>Prompt</type>
      <SyncType>Active</SyncType>
      <ObjectType>
        <type>None</type>
      </ObjectType>
      <SelectedSyncBoxID>0</SelectedSyncBoxID>
      <Message>Please Begin An Active Sync Session.</Message>
    </SmokeTask>
    <SmokeTask xsi:type="Creation">
      <type>Creation</type>
      <SyncType>Active</SyncType>
      <ObjectType>
        <type>Folder</type>
      </ObjectType>
      <SelectedSyncBoxID>0</SelectedSyncBoxID>
      <Name>FolderForTesting</Name>
      <Path>\</Path>
      <CreateNew>true</CreateNew>
    </SmokeTask>
    <SmokeTask xsi:type="Creation">
      <type>Creation</type>
      <SyncType>Active</SyncType>
      <ObjectType>
        <type>File</type>
      </ObjectType>
      <SelectedSyncBoxID>0</SelectedSyncBoxID>
      <Name>mySmallFile.txt</Name>
      <Path>\FolderForTesting\</Path>
      <CreateNew>true</CreateNew>
      <Count>5</Count>
      <ActInTwoFolders>false</ActInTwoFolders>
      <IsLarge>false</IsLarge>
    </SmokeTask>
    <SmokeTask xsi:type="Creation">
      <type>Creation</type>
      <SyncType>Active</SyncType>
      <ObjectType>
        <type>File</type>
      </ObjectType>
      <SelectedSyncBoxID>0</SelectedSyncBoxID>
      <Name>myLargeFile.txt</Name>
      <Path>\FolderForTesting\</Path>
      <CreateNew>true</CreateNew>
      <Count>10</Count>
      <ActInTwoFolders>false</ActInTwoFolders>
      <IsLarge>true</IsLarge>
    </SmokeTask>
    <SmokeTask xsi:type="Prompt">
      <type>Prompt</type>
      <SyncType>Active</SyncType>
      <ObjectType>
        <type>None</type>
      </ObjectType>
      <SelectedSyncBoxID>0</SelectedSyncBoxID>
      <Message>Please wait and confirm that SyncBox File Upload are Complete</Message>
    </SmokeTask>
    <SmokeTask xsi:type="Prompt">
      <type>Prompt</type>
      <SyncType>Active</SyncType>
      <ObjectType>
        <type>None</type>
      </ObjectType>
      <SelectedSyncBoxID>0</SelectedSyncBoxID>
      <Message>Start Second Active Sync Session with Syncbox Id used in initial Sync</Message>
    </SmokeTask>
    <SmokeTask xsi:type="Rename">
      <type>Rename</type>
      <SyncType>Active</SyncType>
      <ObjectType>
        <type>Folder</type>
      </ObjectType>
      <SelectedSyncBoxID>0</SelectedSyncBoxID>
      <OldName>FolderForTesting</OldName>
      <NewName>RenamedSuccessful</NewName>
      <RelativeDirectoryPath>\</RelativeDirectoryPath>
      <ActInTwoFolders>false</ActInTwoFolders>
    </SmokeTask>
  </ScenarioTasks>
</SmokeTest>
<!-- End Task For Testing Host 1 Folder Rename While Host 2 is Mid Sync-->
