=== MatthewMerricks/Cloud/Users/Bob/TestHttpRest/TestHttpRest/Settings/InputParameters.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="InputParameters"
    targetNamespace="http://www.cloud.com/InputParameters.xsd"
    elementFormDefault="qualified"
    xmlns="http://www.cloud.com/InputParameters.xsd"
    xmlns:mstns="http://www.cloud.com/InputParameters.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:annotation>
        <xs:appinfo>Cloud.com InputParameters XML Schema</xs:appinfo>
        <xs:documentation xml:lang="en-us">
            InputParameters.xsd and resulting generated code
            Cloud

            Created by BobS.

            Copyright (c) Cloud.com. All rights reserved.

            Manually copy this copyright declaration to the header of any generated code files created from this schema
        </xs:documentation>
    </xs:annotation>

    <xs:complexType name="Copyright">
        <xs:sequence>
            <xs:element name="FileName" minOccurs="0" maxOccurs="1" type="xs:string" />
            <xs:element name="Copyright" minOccurs="1" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Implementation of InputParameters.xsd XML Schema. Cloud. Copyright (c) Cloud.com. All rights reserved." />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Creator" minOccurs="1" maxOccurs="1" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="InputParams">
        <xs:all>
            <xs:element name="API_Key" type="xs:string" minOccurs="1"/>
            <xs:element name="API_Secret" type="xs:string" minOccurs="1"/>
            <xs:element name="ActiveSyncBoxID" type="xs:int" minOccurs="1"/>
            <xs:element name="ActiveSync_Folder" type="xs:string" minOccurs="1"/>
            <xs:element name="ActiveSync_TraceFolder" type="xs:string" minOccurs="1"/>
            <xs:element name="Token" type="xs:string" minOccurs="0"/>
            <xs:element name="TraceType" type="xs:int" minOccurs="1"/>
            <xs:element name="TraceLevel" type="xs:int" minOccurs="1"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="ParallelTaskSet">
        <xs:choice >
            <xs:element minOccurs="0" maxOccurs="unbounded" name="SmokeTask" type="SmokeTask" />
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="Scenario">
        <xs:choice>
            <xs:element name="ScenarioParallelTaskSet" type="ParallelTaskSet" minOccurs="0" maxOccurs="unbounded" />
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="SmokeTask">
        <xs:sequence>
            <xs:element name="type" >
                <xs:simpleType>
                    <xs:restriction base ="xs:string" >
                        <xs:enumeration value ="HttpTest" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="InnerTask" minOccurs="0" type="SmokeTask" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="HttpTest">
        <xs:complexContent >
            <xs:extension base="SmokeTask" >
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="SmokeTest">
        <xs:complexType>
            <xs:all>
                <xs:element name="Copyright" type="Copyright" />
                <xs:element name="InputParams" type="InputParams" />
                <xs:element name="Scenario" type="Scenario" />
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== MatthewMerricks/Cloud/Users/Bob/TestHttpRest/TestHttpRest/Settings/Settings.xml
<?xml version="1.0" encoding="utf-8" ?>
<SmokeTest xmlns="http://www.cloud.com/InputParameters.xsd"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.cloud.com InputParameters.xsd">
  <Copyright>
      <FileName>Settings.xml</FileName>
      <Copyright>Implementation of InputParameters.xsd XML Schema. Cloud. Copyright (c) Cloud.com. All rights reserved.</Copyright>
      <Creator>BobS</Creator>
  </Copyright>
  <InputParams>
    <API_Key>af5c9411437af584cb31506e0d41b34cfd4b6085bf9b51a5ee480c424b5932ff</API_Key>
    <API_Secret>fc50fff51344faca5ed6cc38e4398e622963d055713db0895a144c8315c5204b</API_Secret>
    <ActiveSync_Folder>"C:\\Users\\Robertste\\Cloud"</ActiveSync_Folder>
    <ActiveSync_TraceFolder>"C:\\Users\Robertste\\Trace"</ActiveSync_TraceFolder>
    <ActiveSyncBoxID>4</ActiveSyncBoxID>
    <Token></Token>
    <TraceLevel>9</TraceLevel>
    <TraceType>5</TraceType>
  </InputParams>
    <Scenario>
        <ScenarioParallelTaskSet>
            <SmokeTask xsi:type="HttpTest">
                <type>HttpTest</type>
            </SmokeTask>
        </ScenarioParallelTaskSet>
    </Scenario>
</SmokeTest>
